MySQL:
  enable: false #se false, vai usar SQLite
  hostname: "host"
  database: "db"
  password: "password"
  port: 3306

#coloque todos os nomes das economias aqui (letras minusculas) e depois coloque todos os comandos na plugin.yml na categoria 'commands'
economies:
  - "cash"
  - "flores"
  - "heads"
  - "money"
  - "tokens"
  - "fragmentos"

#inicial-amount-currency
inicial-amount-cash: 0 #quantidade inicial que vem quando o jogador entra pela primeira vez
inicial-amount-flores: 0
inicial-amount-heads: 0
inicial-amount-money: 4999.9
inicial-amount-tokens: 0
inicial-amount-fragmentos: 0