name: ms-economies
authors: [ ReeachyZ_ ]
version: 1.0.0
main: pt.gongas.economy.EconomyPlugin
description: https://minecraft-solutions.com
commands:
  cash:
  flores:
  heads:
  money:
  tokens:
  fragmentos: